[theme]
primaryColor = "#1f77e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
maxUploadSize = 200

[server]
headless = true
port = 8501
